### PR TITLE
Can now set the ping timeout value

### PR DESCRIPTION
**Pull request by mjwhitta**

### CODE REVIEW

**Comment by bruno-** [comment]
Hey, is there a scenario where a user would need this?

**Comment by mjwhitta** [comment]
At work I have access to some labs that don't have internet access. When the ping works, it returns really quick, but when the machine is unreachable, the default ping timeout seems fairly long. This causes the X to take a while to appear. To make matters worse, it looks like the default refresh rate of the tmux status bar is maybe twice the ping timeout value. So what happens is I see no symbol for ~10 seconds, then I see an X for ~10 secs. Then it repeats. I have considered changing the machine that gets pinged, but then I'm afraid I'll think there is internet access, when there really isn't.

If you are not comfortable merging, I wouldn't be offended. It wouldn't ruin my day. I just thought this was a fairly small change and may be useful to some people.

**Comment by bruno-** [comment]
Hi, yea, we can merge this it's not a biggie.
Question: why is `-W` flag used? There's also a `-t` flag but since I'm not a "ping expert" I'm not sure what's the difference.
Also `-W` is in miliseconds? Will that be ok for people on slow mobile connections?

**Comment by mjwhitta** [comment]
So I chose `-W` because it was the same for OSX and Linux. OSX has a `-t` but Linux has a `-w` instead.   I would prefer to specify my timeout in seconds so I'll make a quick change.

**Comment by bruno-** [comment]
Hey, thanks for the feature. I tweaked it locally before merging (you're still the committer).

I've been thinking about the ping default timeout: is there a reason for keeping this value higher than a couple seconds? I think a dial-up ping roundtrip is less than a second.. anyway, I've changed the default to 3 seconds. Please let me know if there's a reason for keeping this higher and we can change.

**Comment by mjwhitta** [comment]
I only chose 10 because my testing made it look like ping's default was 10. I never looked for the official default. I only saw it take 10 seconds in networks that had no internet connection. I think 3 seconds is a sane default. Thanks!

**Pull request closed without merging**
